[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "itanium_demangler"
version = "1.2"
authors = [
    { name = "whitequark", email = "whitequark@whitequark.org" },
]
description = "Pure Python parser for mangled itanium symbols"
readme = "README.md"
requires-python = ">=3.7"
license = { file = "LICENSE-0BSD.txt" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: BSD License",
]

[project.urls]
"Homepage" = "https://github.com/whitequark/python-itanium_demangler"

[project.optional-dependencies]
test = [
    "pytest",
]
